eureka_client_url: http://localhost:8761/eureka/

##Configuraciones para Spring Actuator:
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info