server:
  port: 8080

##Para que este servicio se registre en Eureka:
spring:
  eureka:
    client:
      service-url:
        defaultZone: ${eureka_client_url}
  cloud:
    gateway:
      routes:
        - id: movieRoute #Identificando la ruta del service de películas
          uri: lb://movie-service #URL donde se hará el redirect según el predicate definido
          predicates: #Reglas de análisis de una request
            - Path=/movies/**
        - id: catalogRoute #Identificando la ruta del service de catálogo de películas
          uri: lb://catalog-service #URL donde se hará el redirect según el predicate definido
          predicates: #Reglas de análisis de una request
            - Path=/catalogs/**
