server:
  port: 8080

##Para que este servicio se registre en Eureka:
spring:
  eureka:
    client:
      service-url:
        defaultZone: ${eureka_client_url}
  cloud:
    gateway:
      routes:
        - id: gameRoute #Identificando la ruta del service de juegos
          uri: lb://game-service #URL donde se hará el redirect según el predicate definido
          predicates: #Reglas de análisis de una request
            - Path=/games/**
        - id: libraryRoute #Identificando la ruta del service de biblioteca de juegos
          uri: lb://library-service #URL donde se hará el redirect según el predicate definido
          predicates: #Reglas de análisis de una request
            - Path=/libraries/**
