eureka_client_url: http://localhost:8761/eureka/

##Configuraciones para Spring Actuator:
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

##Configuraciones para Zipkin:
spring:
  zipkin:
    enabled: true
    baseUrl: http://zipkin:9411