server:
  port: 8084

##Para que este servicio se registre en Eureka:
spring:
  eureka:
    client:
      service-url:
        defaultZone: ${eureka_client_url}

##Info para Spring Actuator:
info:
  app:
    name: movie-service
    description: Movie Service created for QA environment.
    version: 1.0.0