server:
  port: 8082

##Para que este servicio se registre en Eureka:
spring:
  eureka:
    client:
      service-url:
        defaultZone: ${eureka_client_url}

##Info para Spring Actuator:
info:
  app:
    name: animal-service
    description: Animal Service created for development environment.
    version: 1.0.0